"""Refresh the home-page slideshow from the club's public Google Drive folder.

Run this after adding photos to the folder:

    python update-photos.py

It reads the folder's public listing and rewrites photos.js with every image's
Drive ID (videos are skipped). The folder must be shared as
"Anyone with the link -> Viewer". Uses only the Python standard library.
"""
import datetime
import html
import json
import re
import sys
import urllib.request

FOLDER_URL = "https://drive.google.com/drive/folders/1AsU9HAFkrSXT7cp5UNkjjno0jdINid_B?usp=sharing"
IMAGE_EXTENSIONS = {"jpg", "jpeg", "png", "webp", "heic", "gif"}

folder_id = re.search(r"/folders/([A-Za-z0-9_-]+)", FOLDER_URL).group(1)
request = urllib.request.Request(
    f"https://drive.google.com/embeddedfolderview?id={folder_id}",
    headers={"User-Agent": "Mozilla/5.0"},
)
try:
    page = urllib.request.urlopen(request, timeout=30).read().decode("utf-8")
except Exception as error:
    sys.exit(f"Could not read the folder ({error}). Is it shared as 'Anyone with the link'?")

entries = re.findall(
    r'<div class="flip-entry" id="entry-([A-Za-z0-9_-]+)".*?<a href="([^"]+)".*?flip-entry-title">([^<]*)<',
    page, re.S)
photos = [
    {"id": file_id, "name": html.unescape(name)}
    for file_id, link, name in entries
    if "/file/d/" in link and name.rsplit(".", 1)[-1].lower() in IMAGE_EXTENSIONS
]
if not photos:
    sys.exit("No photos found. Check the folder link and its sharing settings.")

data = {"folderUrl": FOLDER_URL, "updated": datetime.date.today().isoformat(), "ids": [p["id"] for p in photos]}
with open("photos.js", "w", encoding="utf-8", newline="\n") as file:
    file.write("// Generated by update-photos.py — do not edit by hand. Rerun the script after adding photos.\n")
    file.write("window.CLUB_PHOTOS = " + json.dumps(data, indent=1) + ";\n")
print(f"photos.js updated with {len(photos)} photos.")
